//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Burdeneds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Burdeneds()
        {
            this.Hospitalizations = new HashSet<Hospitalizations>();
        }
        [Required(ErrorMessage = "השדה נדרש!")]
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "הכנס תווים בין הספרות 0-9")]//תווים בין 0-9
        [MaxLength(9), MinLength(9)]
        //[StringLength(9, ErrorMessage = "הכנס 9 תווים")]
        public string Id { get; set; }

        [Required(ErrorMessage = "השדה נדרש!")]
        [RegularExpression("(^[א-ת]+$)", ErrorMessage = "ניתן להכניס תווים בין א' ל-ת'")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "השדה נדרש!")]
        [RegularExpression("(^[א-ת]+$)", ErrorMessage = "ניתן להכניס תווים בין א' ל-ת'")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "השדה נדרש!")]
        [DataType(DataType.Date)]//תצוגה של הטיפוס
        public System.DateTime BirthDate { get; set; }

        [Required(ErrorMessage = "השדה נדרש!")]
        public string Address { get; set; }

        [Required(ErrorMessage = "השדה נדרש!")]
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "הכנס ספרות בין 0-9")]//תווים בין 0-9
        [DataType(DataType.PhoneNumber)]//תצוגה של הטיפוס
        [MaxLength(10), MinLength(10)]
        [StringLength(10, ErrorMessage = "הכנס 10 תווים")]
        public string Phone { get; set; }

        [DataType(DataType.EmailAddress)]//תצוגה של הטיפוס
        public string Email { get; set; }
        public int CodeContact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospitalizations> Hospitalizations { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
