//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalizationBeds
    {
        public int CodeHospitalizationBed { get; set; }
        public int CodeHospitalization { get; set; }
        public int CodeBed { get; set; }
        public System.DateTime BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string IDAchievementPlacemen { get; set; }
    
        public virtual Beds Beds { get; set; }
        public virtual Hospitalizations Hospitalizations { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
