//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospitalizations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hospitalizations()
        {
            this.HospitalizationBeds = new HashSet<HospitalizationBeds>();
            this.HospitalizationMedicine = new HashSet<HospitalizationMedicine>();
        }
    
        public int CodeHospitalization { get; set; }
        public string IdBurdened { get; set; }
        public System.DateTime EnteringDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public int CodeDepartment { get; set; }
        public string IdDrHospitalize { get; set; }
        public string IdDrLiberator { get; set; }
    
        public virtual Burdeneds Burdeneds { get; set; }
        public virtual Departments Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalizationBeds> HospitalizationBeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalizationMedicine> HospitalizationMedicine { get; set; }
        public virtual Workers Workers { get; set; }
        public virtual Workers Workers1 { get; set; }
    }
}
