//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalizationMedicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HospitalizationMedicine()
        {
            this.HourForMedicine = new HashSet<HourForMedicine>();
        }
    
        public int CodeHospitalizationMedicine { get; set; }
        public int CodeHospitalizatin { get; set; }
        public int codeMedicine { get; set; }
        public string IdDrMentor { get; set; }
    
        public virtual Hospitalizations Hospitalizations { get; set; }
        public virtual Medicines Medicines { get; set; }
        public virtual Workers Workers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HourForMedicine> HourForMedicine { get; set; }
    }
}
