//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HourForMedicine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HourForMedicine()
        {
            this.TakeMedicine = new HashSet<TakeMedicine>();
        }
    
        public int CodeHourForMedicine { get; set; }
        public int CodeMedicineToHospitalize { get; set; }
        public string Hour { get; set; }
        public string Dosage { get; set; }
        public string SpecialInstructions { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual HospitalizationMedicine HospitalizationMedicine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakeMedicine> TakeMedicine { get; set; }
    }
}
