//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicines
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicines()
        {
            this.HospitalizationMedicine = new HashSet<HospitalizationMedicine>();
        }
    
        public int CodeMedicine { get; set; }
        public string MedicineName { get; set; }
        public int CodeKind { get; set; }
        public double SpectrumHours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalizationMedicine> HospitalizationMedicine { get; set; }
        public virtual MedicinesKind MedicinesKind { get; set; }
    }
}
