//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicinesEntities : DbContext
    {
        public MedicinesEntities()
            : base("name=MedicinesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beds> Beds { get; set; }
        public virtual DbSet<Burdeneds> Burdeneds { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<HospitalizationBeds> HospitalizationBeds { get; set; }
        public virtual DbSet<HospitalizationMedicine> HospitalizationMedicine { get; set; }
        public virtual DbSet<Hospitalizations> Hospitalizations { get; set; }
        public virtual DbSet<HourForMedicine> HourForMedicine { get; set; }
        public virtual DbSet<Medicines> Medicines { get; set; }
        public virtual DbSet<MedicinesKind> MedicinesKind { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Rooms> Rooms { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TakeMedicine> TakeMedicine { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
    }
}
