//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TakeMedicine
    {
        public int CodeTaking { get; set; }
        public int CodeHourForMedicine { get; set; }
        public System.DateTime TimeTaking { get; set; }
        public string Dosage { get; set; }
        public string IdGivingMedicine { get; set; }
        public string SpecialNotes { get; set; }
    
        public virtual HourForMedicine HourForMedicine { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
