//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medicine.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Workers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workers()
        {
            this.Departments = new HashSet<Departments>();
            this.HospitalizationBeds = new HashSet<HospitalizationBeds>();
            this.HospitalizationMedicine = new HashSet<HospitalizationMedicine>();
            this.Hospitalizations = new HashSet<Hospitalizations>();
            this.Hospitalizations1 = new HashSet<Hospitalizations>();
            this.TakeMedicine = new HashSet<TakeMedicine>();
        }
        [Required(ErrorMessage = "השדה נדרש!")]
        [RegularExpression("(^[0-9]+$)", ErrorMessage = "הכנס תווים בין הספרות 0-9")]//תווים בין 0-9
        [MaxLength(9), MinLength(9)]
        //[MaxLength(9), MinLength(9), StringLength(9, ErrorMessage = "הכנס 9 תווים")]
        public string Id { get; set; }

        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "השדה נדרש!")]
        [RegularExpression("(^[א-ת]+$)", ErrorMessage = "ניתן להכניס תווים בין א' ל-ת'")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "השדה נדרש!")]
        [RegularExpression("(^[א-ת]+$)", ErrorMessage = "ניתן להכניס תווים בין א' ל-ת'")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "השדה נדרש!")]
        [DataType(DataType.PhoneNumber)]//תצוגה של הטיפוס
        [MaxLength(10), MinLength(10)]
        [StringLength(10, ErrorMessage = "הכנס 10 תווים")]
        public string Phone { get; set; }

        [Required(ErrorMessage = "השדה נדרש!")]
        [DataType(DataType.EmailAddress)]//תצוגה של הטיפוס
        public string Email { get; set; }

        [Required(ErrorMessage = "השדה נדרש!")]
        [Range(1, 4)]
        public int CodeRole { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Departments> Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalizationBeds> HospitalizationBeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalizationMedicine> HospitalizationMedicine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospitalizations> Hospitalizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hospitalizations> Hospitalizations1 { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TakeMedicine> TakeMedicine { get; set; }
    }
}
